Ajout knex
CQEN-QDCE/Radar-NumeriQc-API pull request #5
Opened 2020-12-01 23:20 UTC by vorge

2020-12-04 20:36 UTC, gagf01 requested changes

2020-12-04 20:36 UTC, gagf01 commented on postgresql/populate_tables.sql
> +INSERT INTO public.axes
À quoi le prefix public ?

2020-12-04 20:36 UTC, gagf01 commented on package.json
>  }
Ça serait bien d'avoir des commandes dans la section scripts qui permettent d'initialiser la bd, créer les données et de se mettre à jour.

2020-12-04 20:36 UTC, gagf01 commented on postgresql/Dockerfile
> +FROM postgres:latest
Je crois que ce serait plus safe de viser une version majeure en particulier, pour éviter un changement de version lors d'un redéploiement.

2020-12-04 20:36 UTC, gagf01 commented on postgresql/knexfile.js
> +  }
Pas nécéssaire de garder plusieurs config, il y aura toujours qu'une seule bd par déploiement.

2020-12-04 20:36 UTC, gagf01 commented on postgresql/start_container.sh
> +    docker start radarAPI_database
Le nom (radarAPI_database) ne correspond pas à celui de la commande "docker run" (radar_api_database)

2020-12-07 15:10 UTC, vorge commented on postgresql/populate_tables.sql
> +INSERT INTO public.axes
À spécifier le nom du schema où on veut appliquer la requête. C'est une bonne pratique de toujours le spécifier pour éviter des problèmes lorsqu'on en a plusieurs. J'imagine qu'on ne pense pas avoir d'autres schemas pour la bd dans ce projet, donc c'est probablement pas nécessaire pour ce cas spécifique. Je peux l'enlever si tu préfères.

2020-12-08 13:39 UTC, gagf01 approved these changes

2020-12-08 13:39 UTC, merged